# PowerSync Configuration
# This config connects PowerSync to the existing PostgreSQL database

# Settings for source database replication
replication:
  connections:
    - type: postgresql
      uri: postgresql://pantry_app:pantry_pass@postgres:5432/pantry
      sslmode: disable

# Connection settings for sync bucket storage (using MongoDB)
storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync

# The port which the PowerSync API server will listen on
port: 8080

# Sync rules - define which data to sync to clients
sync_rules:
  content: |
    bucket_definitions:
      # Version 1.0 - Current standard user data bucket
      user_data_v1:
        parameters: 
          - SELECT request.user_id() AS user_id
            WHERE request.parameters() ->> 'schema_version' = '1'
        data:
          # Own user record
          - SELECT * FROM "user" WHERE id = bucket.user_id
          # Users managed by this user (family members)
          - SELECT * FROM "user" WHERE managed_by = bucket.user_id

      # Version 1.0 - Current standard households data bucket  
      user_households_v1:
        parameters: 
          - SELECT household_id FROM household_member WHERE user_id = request.user_id()
            AND request.parameters() ->> 'schema_version' = '1'
        data:
          # Households user is member of
          - SELECT * FROM household WHERE id = bucket.household_id
          # Household memberships for accessible households
          - SELECT * FROM household_member WHERE household_id = bucket.household_id
          # Pantries in accessible households
          - SELECT * FROM pantry WHERE household_id = bucket.household_id
          # Messages in accessible households
          - SELECT * FROM message WHERE household_id = bucket.household_id
          # Typing indicators for accessible households
          - SELECT * FROM typing_indicator WHERE household_id = bucket.household_id

      # Version 1.0 - Current standard message reads
      user_message_reads_v1:
        parameters: 
          - SELECT request.user_id() AS user_id
            WHERE request.parameters() ->> 'schema_version' = '1'
        data:
          # Only own message read status
          - SELECT * FROM message_read WHERE user_id = bucket.user_id

# Settings for client authentication
client_auth:
  # Use the API's JWKS endpoint for JWT validation
  jwks_uri: http://api:3001/api/powersync/jwks
  audience: ['powersync-dev', 'pantry']

  # Schema version support for client evolution
  # Clients must include schema_version in request parameters
  # Format: "1", "2", "3", etc.
  #
  # Current Version Strategy:
  # - v1: Current household-based sync rules (all existing clients)
  # - Future versions can be added with optimized sync rules
  #
  # Usage in sync rules:
  # - request.parameters() ->> 'schema_version' = '1' filters for v1 clients
  # - Each bucket definition includes schema version filtering
  # - Clients must send schema_version parameter to receive data
  # - Household access is determined by explicit membership
  # - Future: Add new bucket definitions for newer schema versions

# Settings for telemetry reporting
telemetry:
  disable_telemetry_sharing: true
