services:
  jeeves-test-postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    environment:
      - POSTGRES_DB=jeeves_test
      - POSTGRES_USER=jeeves_test
      - POSTGRES_PASSWORD=jeeves_test_pass
      - TZ=UTC
      - PGTZ=UTC
    command: |
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=jeeves_test
      -c wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jeeves_test -d jeeves_test"]
      interval: 2s
      timeout: 1s
      retries: 10
    networks:
      - jeeves-test-network
    # Use tmpfs for faster test database (data in memory)
    tmpfs:
      - /var/lib/postgresql/data

  jeeves-test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Use different port to avoid conflicts
    command: redis-server --appendonly no --save ""  # Disable persistence for tests
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 10
    networks:
      - jeeves-test-network
    # Use tmpfs for faster test redis (data in memory)
    tmpfs:
      - /data

networks:
  jeeves-test-network:
    driver: bridge