# SwiftLint Configuration for Pantry iOS App

# Paths
included:
  - Sources
  - Tests
excluded:
  - Sources/PantryCore/Generated
  - .build
  - Package.swift

# Rules Configuration
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule Configuration
force_unwrapping:
  severity: error

identifier_name:
  excluded:
    - id
    - db
    - vm
    - vc

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 40
  error: 60

cyclomatic_complexity:
  warning: 10
  error: 20

# Custom Rules for Pantry
custom_rules:
  hardcoded_text_string:
    name: "Hardcoded Text String"
    regex: 'Text\s*\(\s*"[^"]+"\s*\)'
    message: "Consider using localized strings instead of hardcoded text"
    severity: warning
    match_kinds:
      - identifier
      - keyword
    excluded:
      - "PreviewProvider.swift"
      - "*Tests.swift"
      - "*Preview.swift"
      - "*Mock*.swift"
      
  hardcoded_label_string:
    name: "Hardcoded Label String"
    regex: 'Label\s*\(\s*"[^"]+"\s*,'
    message: "Consider using localized strings in Label"
    severity: warning
    match_kinds:
      - identifier
      - keyword
    excluded:
      - "PreviewProvider.swift"
      - "*Tests.swift"
      - "*Preview.swift"
      - "*Mock*.swift"
      
  hardcoded_button_string:
    name: "Hardcoded Button String"
    regex: 'Button\s*\(\s*"[^"]+"\s*\)'
    message: "Consider using localized strings in Button"
    severity: warning
    match_kinds:
      - identifier
      - keyword
    excluded:
      - "PreviewProvider.swift"
      - "*Tests.swift"
      - "*Preview.swift"
      - "*Mock*.swift"
      
  hardcoded_navigation_title:
    name: "Hardcoded Navigation Title"
    regex: '\.navigationTitle\s*\(\s*"[^"]+"\s*\)'
    message: "Consider using localized navigation titles"
    severity: warning
    match_kinds:
      - identifier
    excluded:
      - "PreviewProvider.swift"
      - "*Tests.swift"
      - "*Preview.swift"
      - "*Mock*.swift"

# Reporter
reporter: "xcode"