name: Jeeves
options:
  bundleIdPrefix: com.jeevesapp
  deploymentTarget:
    iOS: 18.0
  createIntermediateGroups: true
  developmentLanguage: en
  groupSortPosition: bottom
  xcodeVersion: 16.0
  
packages:
  local:
    path: .
    
targets:
  Jeeves:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - path: Jeeves/Jeeves
        createIntermediateGroups: true
    dependencies:
      - package: local
        product: JeevesKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeevesapp.app
        PRODUCT_NAME: Jeeves
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 6.1
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Jeeves
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "Jeeves/Jeeves"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          ENABLE_DEBUG_DYLIB: YES
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule

schemes:
  Jeeves:
    build:
      targets:
        Jeeves: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1":
          enabled: false
      environmentVariables:
        OS_ACTIVITY_MODE:
          value: "debug"
          isEnabled: true
        OS_ACTIVITY_DT_MODE:
          value: "YES"
          isEnabled: true
        CFNETWORK_DIAGNOSTICS:
          value: "3"
          isEnabled: false
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release